### Lars Gabriel, Fabian Wilde, Katharina Hoff & Mario Stanke - University of Greifswald

# Advanced Python course - Session 3/3
<br>
<font size="3">
<b>Contact:</b> katharina.hoff@uni-greifswald.de
<br>
</font>

# 1. NumPy (Numerical Python)
<font size="3">
    NumPy is a Python library that stands for "Numerical Python." It is a fundamental package for scientific computing with Python, providing support for large, multi-dimensional arrays and matrices, along with a wide range of mathematical functions to operate on these arrays. NumPy is widely used in the fields of data science, machine learning, artificial intelligence, and scientific research.<br>
    b>Numpy</b> is a powerful 3rd party package offering the new data type of the <b><i>numpy array</i></b> (numpy.ndarray) with a more powerful and faster implementation in C++ in the background. In contrast to lists in Python, <b>the size of a numpy array cannot be changed and the best practice is to allocate space in advance by initializing an empty array (e.g. filled with zeros)</b>. Also, the data type of its elements shouldn't differ and the number of elements in each row or column has to be the same, since <b>the numpy array represents a N x M matrix</b>.<br>
Some of the key features of NumPy are:
    <ul>
    <li> NumPy arrays are faster and more efficient than Python lists, especially for large datasets.
    <li> NumPy arrays can be multi-dimensional, making it easy to work with matrices and arrays of any dimensionality.
    <li> NumPy provides a large number of mathematical functions, including those for linear algebra, Fourier analysis, random number generation, and more.
    <li> NumPy is open-source and freely available, making it accessible to anyone who wants to use it.
    </ul>
<div align="center">
<img src="img/numpy_nature.webp" width="100%">
</div>
</font>

<font size="3">For using Numpy, you have to import the package once. Since you will in the following often have to refer to numpy, we assign an alias that is faster to type (np):</font>

In [ ]:
# import numpy with alias np
import numpy as np

### NumPy Array

<br>
<font size="3">A NumPy Array can have many dimensions. Let's start with one (similar to a Python list) and two dimensions (similar to a matrix):</font>

In [ ]:
# create a numpy array from a list
my_list = [1.0,2.35,3.141]
arr1 = np.array(my_list)
print("type(my_list) =", type(my_list))
print("type(arr1) =", type(arr1))
print("arr1 =", arr1)

In [ ]:
# create an 2D array / a 3x3 matrix filled with zeros
arr2 = np.zeros((3,3))
print("type(arr2) =", type(arr2))
print("arr2 =", arr2, sep="\n")

In [ ]:
# create a numpy array filled with a specific value
arr3 = np.full((3,2), 2)
print("arr3 =", arr3, sep="\n")

In [ ]:
# index an array element in a multi-dimensional array
arr2 = np.zeros((3,3))
print("arr2 =", arr2, sep="\n")
print()
arr2[0,0] = 1
arr2[1,1] = 2
arr2[2,2] = 3
print("type(arr2) = "+str(type(arr2)))
print("arr2 = \n"+str(arr2))

In [ ]:
# using the attribute "size" of the numpy array is more reliable than using the len() function
# the attribute "shape" contains a tuple with the array or matrix dimensions
print("arr2.size = "+str(arr2.size))
# convention for the shape tuple: (number of rows, number of columns) in case of a 2D array
print("arr2.shape = "+str(arr2.shape))

#### More Indexing

Indexing and slicing works just like with Python `list`s

In [ ]:
data = np.array([1, 2, 3])

print("data[1]:  ", data[1])
print("data[0:2]:", data[0:2])
print("data[1:]: ", data[1:])
print("data[-2:]:", data[-2:])

With higher-dimensional arrays, you can put a comma-separated list of indices in the `[ ]` operator. The `:` means that you want a slice of _all_ values in the respective dimension

In [ ]:
arr4 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("arr4\n", arr4, "\n")
print("arr4[2,1]", arr4[2,1], "\n")
print("arr4[0,:]", arr4[0,:], "\n")
print("arr4[0]  ", arr4[0], "\n")
print("arr4[:,0]", arr4[:,0], "\n")
print("arr4[0:2,1:3]\n", arr4[0:2,1:3])

<font size="3"><div class="alert alert-warning"><b>Exercise 1.1:</b><br>
Practice using Numpy! Create a 3-dimensional Numpy array with zeros of the shape `(3,2,4)`.<br>
Replace the first <i>2 x 4</i> matrix with an array of the same shape (`(2,4)`), containing only twos.<br>
In the second <i>2 x 4</i> matrix, write all numbers from 0 to 7.<br>
In the third <i>2 x 4</i> matrix, store the result of the element-wise multiplication of the first two matrices
</div>

Hints:
* `np.array([1,2,3,4]) * 2` results in the array `[2,4,6,8]`
    
* `np.array([1,2,3,4]) * np.array([1,2,3,4])` performs element-wise multiplication and results in `[1,4,9,16]`
    
The result should look like this:
    
    [[[ 2.  2.  2.  2.]
      [ 2.  2.  2.  2.]]

     [[ 0.  1.  2.  3.]
      [ 4.  5.  6.  7.]]

     [[ 0.  2.  4.  6.]
      [ 8. 10. 12. 14.]]]
    
or this
    
    [[[ 2.  2.  2.  2.]
      [ 2.  2.  2.  2.]]

     [[ 0.  2.  4.  6.]
      [ 1.  3.  5.  7.]]

     [[ 0.  4.  8. 12.]
      [ 2.  6. 10. 14.]]]

In [ ]:
# ====== ENTER YOUR CODE HERE =======

In [ ]:
# ========= SOLUTION =========

x = np.zeros((3,2,4))

x[0] = np.ones((2,4)) * 2

v = 0
for i in range(2):
    for j in range(4):
        x[1,i,j] = v
        v += 1
        
x[2] = x[0]*x[1]
print(x)

<font size="3"><b>Sometimes you want or need to change the shape of your numpy array using the reshape method:</b></font>

In [ ]:
# defines a numpy array with row number unequal column number
arr3 = np.array([[2,3],[3,5],[6,4]])
print("content of arr3:")
print(arr3)

In [ ]:
# prints the shape (number of rows, number of columns)
print("shape of arr3:")
print(arr3.shape)

In [ ]:
# transposes the array / matrix
arr3 = arr3.T
print("transposed array (rows and columns interchanged):")
print(arr3)

In [ ]:
# prints the shape of the transposed array
print("shape of the transposed arr3:")
print(arr3.shape)

In [ ]:
# changing the shape could be achieved using the reshape method expecting a tuple 
# (total number of elements needs to be the same!)
arr3 = np.array([[2,3],[3,5],[6,4]]) # reset array to original
arr3 = arr3.reshape(2,3)
print(arr3) # note that the order of elements might be different from arr3.T

<font size="3"><b>Often you would like to perform computations over an entire row or column of your array (hence your dataset) for some statistical evaluation, like:
    </b></font>

In [ ]:
# generates a 2D matrix of random floating-point numbers
# np.random.normal generates normally distributed random numbers and expects (mean, standard deviation, size=(a,b))
arr = np.random.normal(0,2,size=(6,8))
print("random number array:")
print(arr)

In [ ]:
# sums all values in each column
col_sum = np.sum(arr, axis=0)
print("col_sum = "+str(col_sum))

In [ ]:
# sums all values in each row
row_sum = np.sum(arr, axis=1)
print("row_sum = "+str(row_sum))

In [ ]:
# multiplies all values in each column
col_prod = np.prod(arr, axis=0)
print("col_prod = "+str(col_prod))

In [ ]:
# multiplies all values in each row
row_prod = np.prod(arr, axis=1)
print("row_prod = "+str(row_prod))

In [ ]:
# calculate mean
total_mean = np.mean(arr)
print("Overall mean:"+str(total_mean))
# calculate standard deviation
total_std = np.std(arr)
print("Overall standard deviation:"+str(total_std))

In [ ]:
# calculate mean over all elements in a column (iterates over first array dimension)
col_mean = np.mean(arr, axis=0)
print(col_mean)

In [ ]:
# calculate mean over all elements in a row (iterates over second array dimension)
row_mean = np.mean(arr, axis=1)
print(row_mean)

#### Numpy Performance

Other than being very convenient to use, these Numpy functions also speed up your code!  

Take for example the sum of all matrix elements. One could compute this manually by accessing all the elements and summing up on the way

As we will see, numpy functions are much faster!

In [ ]:
import time # load the module time, contains functions to measure time

big_array = np.random.normal(0,2,size=(1000,8000)) # large array with 8 million elements

# manual sum calculation
start_timepoint = time.time() # store the current time
manual_sum = 0
for i in range(0, 1000):
    for j in range(0, 8000):
        manual_sum += big_array[i,j]

duration = time.time() - start_timepoint # calculate how many seconds have passed since `start_timepoint` and now
print(manual_sum, "\nManual calculation took", duration, "s")
print()

# numpy sum
start_timepoint = time.time() # store the current time
np_sum = big_array.sum()
duration = time.time() - start_timepoint # calculate how many seconds have passed since `start_timepoint` and now
print(np_sum, "\nNumpy calculation took", duration, "s")

<font size="3"><div class="alert alert-warning"><b>Exercise 1.2:</b><br>
Suppose you are given two arrays of shape (3, 4):
Write a program using NumPy that performs the following operations:
    <ul>
    <li> Compute the element-wise sum of the two arrays and store the result in a new array c.
    <li> Compute the dot product of the two arrays and store the result in a new array d.
    <li> Reshape c into an array of shape (2, 6) and store the result in a new array e.
    <li> Compute the element-wise product of the first two rows of e and store the result in a new array f.
    <li> Compute the transpose of f and store the result in a new array g.
    <li> Compute the sum of the elements in g and print the result.
    </ul>
</div>

In [ ]:
import numpy as np 

a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
b = np.array([[12, 11, 10, 9], [8, 7, 6, 5], [4, 3, 2, 1]])

# ====== ENTER YOUR CODE HERE =======

In [ ]:
# ========= SOLUTION =========

import numpy as np

# Given arrays
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
b = np.array([[12, 11, 10, 9], [8, 7, 6, 5], [4, 3, 2, 1]])

# Element-wise sum of a and b
c = a + b

# Dot product of a and b
d = np.dot(a, b.T)

# Reshape c into an array of shape (2, 6)
e = c.reshape(2, 6)
print(e)
# Element-wise product of the first two rows of e
f = e[0, :] * e[1,:]
# Transpose of f
g = f.T

# Sum of the elements in g
result = np.sum(g)

print(result)

<font size="3"><div class="alert alert-warning"><b>Exercise 1.3:</b><br>
Create a NumPy array of shape (4, 5) containing random integers in the range from 1 to 100, and perform the following operations:
    <ul>
    <li> Calculate the mean and median of the array.
    <li> Reshape the array into an array of shape (5, 4).
    <li> Calculate the standard deviation of the reshaped array along the first axis.
    <li> Replace all the elements in the original array that are greater than the median with the value 0.
    <li> Print the resulting array after step 4.
    </ul>
</div>

In [ ]:
# ====== ENTER YOUR CODE HERE =======

In [ ]:
# ========= SOLUTION =========

import numpy as np

# Create a NumPy array of shape (4, 5) containing random integers in the range from 1 to 100
arr = np.random.randint(1, 101, size=(4, 5))

# Calculate the mean and median of the array
mean = np.mean(arr)
median = np.median(arr)

# Reshape the array into an array of shape (5, 4)
arr_reshaped = arr.reshape(5, 4)

# Calculate the standard deviation of the reshaped array along the first axis
std_dev = np.std(arr_reshaped, axis=0)

# Replace all the elements in the original array that are greater than the median with the value 0
arr[arr > median] = 0

# Print the resulting array after step 4
print(arr)


# Visualizing Data with Matplotlib
<br>
<font size="3">
    <b>One picture can say more than 1000 words:</b> Visualizing your data is probably the most important aspect in your daily work routine. <a href="https://matplotlib.org/">Matplotlib</a> is the most common Python package for data visualization offering a multitude of different plot types and options to tailor the plots according to your needs. Even Latex can be used to obtain nice looking plot titles, axes labels and annotations.<br><br>
    <a href="https://matplotlib.org/stable/gallery/index.html">See a plot gallery here</a> of all the possibilities and functions matplotlib offers out-of-the-box.
</font>

### Example 1:

<font size="3">First you need to import the pyplot function from matplotlib using</font>

In [ ]:
import matplotlib.pyplot as plt
import numpy as np

In [ ]:
x = np.linspace(0, 2*np.pi, 100)
y = np.sin(x) 
y

<font size="3">Then we plot a simple sine:</font>

In [ ]:
# array [0, .01, .02, ..., 2*3.14]
# one option is np.arange
#x = np.arange(start = 0, stop = 2 * np.pi, step = 0.01) 
# another option is np.linspace
x = np.linspace(0, 2*np.pi, 100)
# applies sine elementwise
y = np.sin(x) 
# data for the 2nd graph
y2 = np.cos(x)

# figure size and resolution in dpi (dots per inch)
width_px = 640
height_px = 480
dpi = 100
# create a figure
fig = plt.figure(figsize=(width_px/dpi, height_px/dpi), dpi=dpi)
# create a new plot
ax = fig.add_subplot()
# create the plot
ax.plot(x, y, label="graph 1")
ax.plot(x, y2, color="red", label="graph 2")
# adds a grid
ax.grid(which="both", color="gray", linestyle=":")
# semicolon suppresses output of last line in cell
ax.set_title("Sine Wave"); 
ax.set_xlabel("x");
ax.set_ylabel("y");
# adds a legend for the graphs in the plot
ax.legend(loc="upper right")
plt.show()

In [ ]:
# array [0, .01, .02, ..., 2*3.14]
# one option is np.arange
# x = np.arange(start = 0, stop = 2 * np.pi, step = 0.01) 
# another option is np.linspace
x = np.linspace(0, 2*np.pi, 20)
# applies sine elementwise
y = np.sin(x) 
# data for the 2nd graph
y2 = np.cos(x)

# figure size and resolution in dpi (dots per inch)
width_px = 640
height_px = 480
dpi = 100
# create a figure
fig = plt.figure(figsize=(width_px/dpi, height_px/dpi), dpi=dpi)
# create a new plot
ax = fig.add_subplot()
# create the plot
ax.scatter(x, y, label="graph 1")
ax.scatter(x, y2, color="red", label="graph 2")
# adds a grid
ax.grid(which="both", color="gray", linestyle=":")
# semicolon suppresses output of last line in cell
ax.set_title("Sine Wave"); 
ax.set_xlabel("x");
ax.set_ylabel("y");
# adds a legend for the graphs in the plot
ax.legend(loc="upper right")
plt.show()

In [ ]:
# generates an array with normal distributed random values
N = int(1E4)
x = np.random.normal(0, 1, (N,))
# applies sine elementwise
y = np.random.normal(0, 1, (N,))

# figure size and resolution in dpi (dots per inch)
width_px = 640
height_px = 480
dpi = 100
# create a figure
fig = plt.figure(figsize=(width_px/dpi, height_px/dpi), dpi=dpi)
# create a new plot
ax = fig.add_subplot()
# create the plot
ax.scatter(x, y, label="graph 1", s=1, color="black", marker=".")
# adds a grid
ax.grid(which="both", color="gray", linestyle=":")
# semicolon suppresses output of last line in cell
ax.set_title("Random values"); 
ax.set_xlabel("x");
ax.set_ylabel("y");
# adds a legend for the graphs in the plot
ax.legend(loc="upper right")
plt.show()

### Example 2:

In [ ]:
import matplotlib.pyplot as plt
import numpy as np

# Generate some random data
x = np.linspace(0, 10, 100)
y1 = np.sin(x)
y2 = np.cos(x)

# Create a figure with two subplots
fig, axs = plt.subplots(nrows=1, ncols=2, figsize=(8, 4))

# Plot the first subplot
axs[0].plot(x, y1)
axs[0].set_title('Figure 1')

# Plot the second subplot
axs[1].plot(x, y2, color="red")
axs[1].set_title('Figure 2')

# Set the spacing between subplots
plt.subplots_adjust(wspace=0.3)

# Show the plot
plt.show()


### Example 3:

In [ ]:
Img = np.random.randint(low=0, high=255, size=(100, 100, 3), dtype='B') # B: unsigned byte (0..255)
#print(Img) # Img is a three-dim array
plt.imshow(Img, interpolation="none"); # third dimension interpreted as red, green, blue
# image coordinates are numbered as in matrices, first rows (top to bottom) then columns (left to right)

### More complex Example 4:

<br>
<font size="3">
A more complex example demonstrating almost all capabilities to customize your plot:
</font>

In [ ]:
# a very simple example to begin with
import numpy as np
from matplotlib import pyplot as plt

# generate the data to plot
omega = 1
# yields a numpy array of N equidistant points on the given interval
x = np.linspace(-2*np.pi, 2*np.pi, 100)
y = np.sin(x)

# here you can set the size and resolution of the plot
#resolution in dpi = dots per inch
# for the screen 75 to 120 dpi isfine
# for a publication you'd need to use a higher resolution of 150 or 300 dpi
dpi = 150
# height in inch
height = 3 
# width in inch
width = 4

# initalize the new figure
fig = plt.figure(figsize=(width, height), dpi=dpi)

# Here you could specify multiple plots aside or in a matrix configurationn
# we just want one plot in the figure, 
# thats why we set 111 = number of rows, number of columns, total num of plots
ax = fig.add_subplot(111)

# create the plot itself (a line plot connecting the points)
# plot the sine
ax.plot(x, y, color = "r", linestyle = "--", linewidth = 2, label = "sine")
# plot a constant line at zero
ax.plot(x, np.zeros(x.shape), color = "black", linestyle = "-", linewidth = 2, label = "line")
# plot a graph
ax.plot(x, x, color = "blue", linestyle = ":", linewidth = 1, label = "graph")

# use a grid in the background
ax.grid(which="both", color="gray", linestyle="-.", linewidth=0.5)

# set the plot title using Latex
# the semicolon at the end of the line is to suppress the output of the function
# (one of the rare cases where you'd end a line of Python code with a semicolon)
ax.set_title("A first plot of " + r'$y = \sin\left(2 \pi \omega t\right)$');

# set the axes labels
ax.set_xlabel("x");
ax.set_ylabel(r'$\sum_{i=1}^{N} \frac{1}{i} \psi$');

# normal string definition in Python uses "string"
# in order to use Latex in title or axes label, use r'string'
# Why is that?
# If double quotation marks are used, the string is "processed" and the so-called escape sequences (e.g. \n for a linebreak are replaced)
# If single quotation marks like r'string' are used, the string is stored as it is.

# use the plot legend
# only works if keyword argument 'label' was given to the method plot
ax.legend()

# save the plot in a file
# the file ending determines the format
# valied formats are e.g. jpg, png for raster graphics (will become pixelated if you zoom in and the resolution is too small)
# you can also export the plot as vector graphics with ending .eps (will be rendered at every zoom level)
fig.savefig("plot.png")

### More complex Example 5:

<br>
<font size="3">A histogram plot as more complex example for a plot:</font>

In [ ]:
# a very simple example to begin with
import numpy as np
from matplotlib import pyplot as plt

# generate data to work with
num_values = 1E6
x = np.random.normal(0,1,int(num_values))

# here you can set the size and resolution of the plot
#resolution in dpi = dots per inch
# for the screen 75 to 120 dpi isfine
# for a publication you'd need to use a higher resolution of 150 or 300 dpi
dpi = 150
# height in inch
height = 3 
# width in inch
width = 4

# initalize the new figure
fig = plt.figure(figsize=(width, height), dpi=dpi)

# Here you could specify multiple plots aside or in a matrix configurationn
# we just want one plot in the figure, 
# thats why we set 111 = number of rows, number of columns, total num of plots
ax = fig.add_subplot(111)

# plots a histogram, use parameter density to normalize the vertical axis
h=ax.hist(x, bins=100, color="black", density=True)
ax.set_ylabel("count");
ax.set_xlabel("x");
ax.set_title("A simple histogram")
ax.grid(which="both",color="gray",linewidth=0.5,linestyle="--")
plt.show()

<font size="3">For further options to customize plots, have also a look at the predefined <a href="https://matplotlib.org/3.1.0/gallery/color/named_colors.html">color</a> and <a href="https://matplotlib.org/3.3.1/api/_as_gen/matplotlib.lines.Line2D.html#matplotlib.lines.Line2D.lineStyles">linestyle</a> or <a href="https://matplotlib.org/3.3.1/api/_as_gen/matplotlib.lines.Line2D.html#matplotlib.lines.Line2D.lineStyles">here</a> keywords on the matplotlib website.</b>
</font>

<font size="3">
<div class="alert alert-warning"><b>Exercise 6:</b> Create a plot for the function f(x) = 3x + 2 in the interval [-2, 3] in <b>black</b>. Also plot a horizontal, <b>red</b>, <b>dashed</b> line in the same graph at y = 1.
<br><br>
<b>Hint:</b> Use np.arange or <a href="https://numpy.org/doc/stable/reference/generated/numpy.linspace.html">np.linspace</a> to create an array with x values. Use the style keywords color and linestyle to change the appearance of the graphs. Use <a href="https://numpy.org/doc/stable/reference/generated/numpy.full.html">np.full</a> to create an array filled with a given value.
</div>
</font>

Your figure should look something like this:  
![](img/ex6.png)   

### Try it yourself:

In [ ]:
# ====== ENTER YOUR CODE HERE =======

In [ ]:
# ====== SOLUTION =======
import matplotlib.pyplot as plt
import numpy as np

# creates an array with 100 values between -2 and 3 
x = np.linspace(-2,3,100)
y = 3 * x + 2

# creates an array with 100 elements filled with 1
y2 = np.full(100, 1)

fig, ax = plt.subplots(1,1)
ax.plot(x, y, color="black")
ax.plot(x, y2, color="red", linestyle="-.")
plt.show()

<font size="3">
<div class="alert alert-warning"><b>Exercise 7:</b> Fill out the gaps denoted by '...ENTER CODE HERE...' to produce the Figure shown below.
</div>
</font>

Your figure should look something like this:  
![](img/ex7.png)   

In [ ]:
# ====== ENTER YOUR CODE HERE =======

In [ ]:
# =========== SOLUTION ============

import matplotlib.pyplot as plt
import numpy as np

# Generate some data
x = np.linspace(0, 10, 100)
y1 = np.sin(x)
y2 = np.cos(x)
y3 = np.tan(x)

# Create a figure with two subplots
fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(8, 10))

# Plot the data on the first subplot
ax1.plot(x, y1, label='Sin(x)', color='red')
ax1.plot(x, y2, label='Cos(x)', color='green')
ax1.set_title('Trigonometric Functions')
ax1.legend()

# Add some annotations to the first subplot
ax1.text(0.1, 0.9, 'Some annotation', transform=ax1.transAxes)
ax1.annotate('Maximum', xy=(np.pi/2, 1), xytext=(np.pi/2, 2),
             arrowprops=dict(facecolor='black', shrink=0.05))

# Plot a histogram on the second subplot
mu, sigma = 0, 1
data = np.random.normal(mu, sigma, size=1000)
ax2.hist(data, bins=50, alpha=0.5, color='blue')
ax2.set_title('Normal Distribution')

# Add a vertical line to the second subplot
ax2.axvline(x=mu, linestyle='--', color='black', label='Mean')
ax2.legend()

# Add a global title to the figure
fig.suptitle('Two Subplots with Different Visualizations')

# Show the plot
plt.show()

---

# The library Pandas

<br>
<font size="3">
Neither NumPy arrays, nor any of the native Python data structures (e.g. lists, dicts, ...) are suitable to handle the data that is typically generated in scientific experiments or by surveys. These are typically tables where one column contains one data type, but different columns may have different data types. The solution in Python is to use Pandas (https://pandas.pydata.org/). Pandas is also most popular for time series data.
<br><br>
If we want to use Pandas, we have to import it:
</font>

In [ ]:
import pandas as pd

<font size="3">
With Pandas, we can easily import a csv file that had previously been exported from LibreOffice Calc (or similar Office software):
</font>

In [ ]:
# have a look at the raw file content
with open("data/melon.csv", "rt") as file_handle:
    lines = file_handle.readlines()
    
lines[:10]

In [ ]:
# load the file with pandas
melon = pd.read_csv('data/melon.csv', sep='\t')
melon

<font size="3">We can play with accessing parts of the melon data set:</font>

In [ ]:
#print("access lines 1 and 2, all columns:")
# line index is 0-based
print(melon.iloc[1:3, 0])

In [ ]:
print("access a particular single value as scalar:")
print(melon.iloc[1,1])

In [ ]:
print("access a column by name (only first couple of lines):")
print(melon["yield"].head(10))

In [ ]:
print(melon.head())

In [ ]:
# like in Numpy we can also use comparisons in Pandas when elements are addressed
print("find parts of dataframe where yield >37:")
print(melon[ melon['yield'] > 37 ])

In [ ]:
print("find parts of dataframe where variety is D:")
print(melon[melon['variety'] == 'D'])

In [ ]:
print(melon[melon["variety"] == "C"])

In [ ]:
print(melon.count())

In [ ]:
# count the number of occurrences of this variety
print(melon[melon["variety"] == "C"]["yield"])

In [ ]:
melon["yield"].mean()

In [ ]:
# group-by functionality facilitates analyses
print(melon.groupby("variety").mean())

<font size="3">Table-like data in Pandas is stored in DataFrame objects, as we can see, when we check the datatype of our melon dataset:</font>

In [ ]:
print(type(melon))

<font size="3">A DataFrame can also be created manually from one or more lists or numpy arrays:</font>

In [ ]:
# You can define a name for each column with the parameter columns
# The special thing about Pandas is now that one column can also be defined as index or can
# be explicitly defined. Indexation is a key feature of big databases to speed-up queries.
df = pd.DataFrame([123,23,54,15,89], columns=["numbers"], index=["a","b","c","d","e"])
df

<font size="3">A Pandas DataFrame object also has useful attributes like index and columns:</font>

In [ ]:
print(df.index)
print(df.columns)
print(df.dtypes)

<font size="3">Once defined, a DataFrame can be enlarged as well by other columns even if the columns contain a different data type:</font>

In [ ]:
df['floats'] = [1.23, 5.67, 4.31, 6.89, 5.34]
df['names'] = ['Marco', 'Alex', 'John', 'Michael', 'Alistair']
df

In [ ]:
print(df.dtypes)

<font size="3">Or we simply add a new row with data providing a new DataFrame, but once an index has been defined, we need to make sure to provide then index values as well:</font>

In [ ]:
df.append(pd.DataFrame({'numbers': 273, 'floats': 8.98, 'names': "Florian"}, index=['f']))

<font size="3"><div class="alert alert-warning"><b>Exercise 6.2:</b> 
Use Pandas to load and analyze the data set bike.csv:<br>
        1. Load data/bike.csv as a DataFrame with pandas and call it bike_data.<br>
        2. Summarize/Describe each columns of your data set with key statistical values (mean, std, min, max, number of rows).<br>
        3. Visualize the columns temp (x axis) and count (y axis) as a scatter plot with matplotlib.<br>
        4. Load the second part of the data set (data/bike2.csv) and add the column date to your Data Frame bike_data.<br>
        5. Select all rows with the date '2011-01-20' as a subset from bike_data and store them in a separate DataFrame bike_subset.<br>
        6. Change your plot so that all data points of bike_subset are red and all other data points are blue.
</div>
    
<b>Try to run it yourself here:</b></font>

In [ ]:
# ====== ENTER YOUR CODE HERE =======

#### Example Solution

In [ ]:
import matplotlib.pyplot as plt
import pandas as pd

# Load data set and describe it
bike_data = pd.read_csv("data/bike.csv")
print(bike_data.describe())



In [ ]:
# plot the data as a scatter plot
width = 10
height = 7
dpi = 100
fig = plt.figure(figsize=(width, height), dpi=dpi)
ax = fig.add_subplot()
ax.scatter(bike_data["temp"],  bike_data["count"], )
ax.grid(which="both", color="gray", linestyle=":")
ax.set_title("bike rentals versus temperature"); 
ax.set_xlabel('temperature [' + r'$^\circ$' + 'C]');
ax.set_ylabel('rental count per hour');
plt.show()

In [ ]:
# Load second part of the data set
bike_data2 = pd.read_csv("data/bike2.csv")
print(bike_data2.describe())

# add date as a new column to bike data
bike_data["date"] = bike_data2["date"]

print(bike_data.describe())

# choose the subset for all rows on day 2011-01-20
bike_data_subset = bike_data[bike_data["date"] == "2011-01-20"]

In [ ]:
bike_data_subset

In [ ]:
width = 10
height = 7
dpi = 100
fig = plt.figure(figsize=(width, height), dpi=dpi)
ax = fig.add_subplot()
ax.scatter(bike_data["temp"], bike_data["count"])
ax.scatter(bike_data_subset["temp"], bike_data_subset["count"], color="red")
ax.set_title("bike rental")
ax.set_xlabel("temp")
ax.set_ylabel("counts per hour")
plt.show()